name: mr_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  # flutter pub run flutter_launcher_icons:main
  image_path: "assets/images/logo.png"

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Black.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Light.ttf
        - asset: assets/fonts/Nunito/static/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito/static/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito/static/Nunito-SemiBoldItalic.ttf